### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by austinkwok1997**
Just adding more functions from the Qualtrics API

### CODE REVIEW

**Review by justin0022 — CHANGES_REQUESTED** [review]
Hi Austin, 

It all looks reasonable to me. 
The one suggestion I have is to use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), since it increases readability.

Are you familiar with publishing to NPM? If you run `npm run build`, Rollup will generate a production build that can be published to NPM so it can be reused.

**Comment by austinkwok1997** [comment]
Thanks Justin,

I'll start using template literals. I'm not familiar with publishing to NPM tho I've been using `npm run build` to test the code on my machine.

**Comment by justin0022** [comment]
If you're around on Friday I'll show you how to publish to NPM. It makes it easier to use in different projects.

**Comment by austinkwok1997** [comment]
I work Monday, Tuesday, and Wednesday but I'll try to pop by on Friday

**Comment by austinkwok1997** [comment]
Added template literals

**Review by justin0022 — APPROVED** [review]
LGTM

**Pull request merged**
